### PR TITLE
fix wget filename

### PR DESCRIPTION
**Pull request by liujuncheng**

### CODE REVIEW

**Comment by CutePoisonX** [comment]
Hi! Thanks for your contribution. Just tested your commit and there seems to be no difference in the outcome between the previous version and your commit. Could you just provide a short explanation why you find the -O flag necessary? Thank you!

**Comment by liujuncheng** [comment]
```
 wget http://downloads.sourceforge.net/faac/faac-1.28.tar.gz
--2016-03-07 12:07:54--  http://downloads.sourceforge.net/faac/faac-1.28.tar.gz
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.34.181.59
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response...
  HTTP/1.0 302 Found
  Cache-Control: no-cache
  Connection: close
  Location: http://58.30.31.203:9999/downloads.sourceforge.net/faac/faac-1.28.tar.gz
Location: http://58.30.31.203:9999/downloads.sourceforge.net/faac/faac-1.28.tar.gz [following]
--2016-03-07 12:07:55--  http://58.30.31.203:9999/downloads.sourceforge.net/faac/faac-1.28.tar.gz
Connecting to 58.30.31.203:9999... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 302 Found
  Content-Length: 0
  Cache-Control: no-cache
  Location: http://120.52.72.53:80/downloads.sourceforge.net/c3pr90ntcsf0/faac/faac-1.28.tar.gz
  Date: Mon, 07 Mar 2016 04:07:55 GMT
  Connection: keep-alive
Location: http://120.52.72.53:80/downloads.sourceforge.net/c3pr90ntcsf0/faac/faac-1.28.tar.gz [following]
--2016-03-07 12:07:55--  http://120.52.72.53/downloads.sourceforge.net/c3pr90ntcsf0/faac/faac-1.28.tar.gz
Connecting to 120.52.72.53:80... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 307 Temporary Redirect
  Server: nginx
  Date: Mon, 07 Mar 2016 04:07:56 GMT
  Content-Type: text/html; charset=UTF-8
  Content-Length: 420
  Connection: keep-alive
  Location: http://sourceforge.net/projects/faac/files/faac-src/faac-1.28/faac-1.28.tar.gz/download?use_mirror=nchc
  via: ltgj53 MISS
Location: http://sourceforge.net/projects/faac/files/faac-src/faac-1.28/faac-1.28.tar.gz/download?use_mirror=nchc [following]
--2016-03-07 12:07:56--  http://sourceforge.net/projects/faac/files/faac-src/faac-1.28/faac-1.28.tar.gz/download?use_mirror=nchc
Resolving sourceforge.net (sourceforge.net)... 216.34.181.60
Connecting to sourceforge.net (sourceforge.net)|216.34.181.60|:80... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 301 Moved Permanently
  Server: nginx
  Date: Mon, 07 Mar 2016 04:07:57 GMT
  Content-Type: text/html; charset=UTF-8
  Connection: close
  Location: https://sourceforge.net/projects/faac/files/faac-src/faac-1.28/faac-1.28.tar.gz/download?use_mirror=nchc
  Content-Length: 420
  X-Content-Type-Options: nosniff
Location: https://sourceforge.net/projects/faac/files/faac-src/faac-1.28/faac-1.28.tar.gz/download?use_mirror=nchc [following]
--2016-03-07 12:07:57--  https://sourceforge.net/projects/faac/files/faac-src/faac-1.28/faac-1.28.tar.gz/download?use_mirror=nchc
Connecting to sourceforge.net (sourceforge.net)|216.34.181.60|:443... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  Server: nginx
  Date: Mon, 07 Mar 2016 04:07:58 GMT
  Content-Type: text/html; charset=utf-8
  Connection: close
  Pragma: no-cache
  Cache-Control: no-cache
  X-UA-Compatible: IE=edge,chrome=1
  X-Frame-Options: SAMEORIGIN
  Set-Cookie: VISITOR=56dcfe9ec1c78b5b0bc9ac20; expires="Thu, 05-Mar-2026 04:07:58 GMT"; httponly; Max-Age=315360000; Path=/
  Set-cookie: sourceforge=e6fc161a6d1888be3ba3e88b2f676dad4929060fgAJ9cQEoVQxsYW5kaW5nX3BhZ2VxAlVBL3Byb2plY3RzL2ZhYWMvZmlsZXMvZmFhYy1zcmMvZmFhYy0xLjI4L2ZhYWMtMS4yOC50YXIuZ3ovZG93bmxvYWRxA1UFcHJlZnNxBH1xBVUGZGxoaXN0cQZdcQd9cQgoVQdyZWxlYXNlcQl9cQooVQRkYXRlcQtjZGF0ZXRpbWUKZGF0ZXRpbWUKcQxVCgfZAgoQKwYAAACFUnENVQpzZl9maWxlX2lkcQ5K7gIYAFUIZmlsZW5hbWVxD1gkAAAAL2ZhYWMtc3JjL2ZhYWMtMS4yOC9mYWFjLTEuMjgudGFyLmd6cRB1VQdwcm9qZWN0cRF9cRIoVQlzaG9ydG5hbWVxE1gEAAAAZmFhY3EUVQVzZl9pZHEVTcACVQRuYW1lcRZYHQAAAEZyZWV3YXJlIEFkdmFuY2VkIEF1ZGlvIENvZGVycRd1dWFVA2tleXEYVRg1NmRjZmU5ZWMxYzc4YjViMGJjOWFjMjBxGVUKY3VycmVudF9vc3EaXXEbKFUFd2luMzJxHFUHV2luZG93c3EdZVUDX2lkcR5VIDQzODViYzZmNjk0NTQ3MjhhNTNmMmYzOWU5OGExMDIycR9VDl9hY2Nlc3NlZF90aW1lcSBHQdW3P6ebp6BVDl9jcmVhdGlvbl90aW1lcSFHQdW3P6ebp5x1Lg==; expires=Tue, 19-Jan-2038 03:14:07 GMT; httponly; Path=/; secure
  Content-Length: 59061
  X-Content-Type-Options: nosniff
Length: 59061 (58K) [text/html]
Saving to: 'download?use_mirror=nchc.html'

download?use_mirror=nchc.html                   100%[====================================================================================================>]  57.68K  87.4KB/s    in 0.7s

Last-modified header missing -- time-stamps turned off.
2016-03-07 12:07:59 (87.4 KB/s) - 'download?use_mirror=nchc.html' saved [59061/59061]
```

**Comment by liujuncheng** [comment]
the saved filename is `download?use_mirror=nchc.html`

**Comment by CutePoisonX** [comment]
Ok, seems strange to me but maybe it has to do something with the wget version that is used. Anyway - merged

**Pull request merged**
